wall_post:
    resource: "@WallPostBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

_welcome:
    pattern: /
    defaults: { _controller: WallPostBundle:Default:index }
